baseURL = 'https://blog.19194545.xyz/'
theme = "dream"
defaultContentLanguage = "ja"
languageCode = "ja"
title = 'ぴっぴのライフログ'
hasCJKLanguage = true
[params]
lightTheme = "emerald"
darkTheme = "forest"
headerTitle = "ぴっぴのライフログ"
motto = "べったーべったー、だんだん。"
rss = true
stickyNav = true
description = "ぴっぴの記録～"
avatar = "img/avat.png"
noDefaultSummaryCover = true
showTableOfContents = true
showSummaryCoverInPost = true
imageZoomableInPost = true
showPrevNextPost = true
